# deployment.yaml
apiVersion: apps/v1 # The API resource where this workload resides
kind: Deployment # The kind of workload we're creating
metadata:
  name: game-api # This will be the name of the deployment
spec:
  selector: # Define the wrapping strategy
    matchLabels: # Match all pods with the defined labels
      app: game-api # Labels follow the `name: value` template
  template: # This is the template of the pod inside the deployment
    metadata: # Metadata for the pod
      labels:
        app: game-api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: olacontainerreg3.azurecr.io/gameapi:latest
        #- image: olacontainerreg2.azurecr.io/pythonapidetails:latest #specify image name
          name: game-api
          resources: #amount of resources needed for the pod
            requests: # Minimum amount of resources requested
              cpu: 100m
              memory: 128Mi
            limits: # Maximum amount of resources requested
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 5000 # This container exposes port 80
              name: http # We named that port "http" so we can refer to it later
          env:
            - name: oladbconnkey1
              valueFrom:
                secretKeyRef:
                  name: oladbconnkey1
                  key: cosmos_key
                  optional: false # same as default; "mysecret" must exist
                                  # and include a key named "password"
