name: Docker build/Kubernetes Deployment Workflow

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Docker build/push
      env:
        ACR_NAME: ${{ secrets.ACR_NAME }}
      run: |
        docker build -f gameScoreDocker/Dockerfile . -t $ACR_NAME/gameapi:${{ github.sha }}
        docker push $ACR_NAME/gameapi:${{ github.sha }}
        
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Get AKS credentials
      env:
        CLUSTER_RESOURCE_GROUP_NAME: ${{ secrets.CLUSTER_RESOURCE_GROUP_NAME }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      run: |
        az aks get-credentials \
          --resource-group $CLUSTER_RESOURCE_GROUP_NAME \
          --name $CLUSTER_NAME \
          --overwrite-existing
          
    - name: Deploy application
      uses: Azure/k8s-deploy@v3.1
      with:
          action: deploy
          manifests: |
             KubDeployment/deployment.yml
             KubDeployment/service.yml
          images: |
             $ACR_NAME/gameapi:${{ github.sha }}


    
      
