name: Docker build/Kubernetes Deployment Workflow

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
    
    - name: Read Cosmos DB connection/app Insight connection string from terraform 
      working-directory: ./terraform
      run: |
        echo "Running terraform init..."
        terraform init
        echo "Setting Cosmos DB from Terraform output..."
        COSMOSDB_SECRET="$(terraform output -raw cosmos_key)"
        echo "cosmos_secret=$COSMOSDB_SECRET" >> $GITHUB_ENV

        echo "Reading app Insight Connection String..."
        APPINSIGHT_SECRET="$(terraform output -raw connection_string)"
        echo "insight_secret=$APPINSIGHT_SECRET" >> $GITHUB_ENV
    
    
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Docker build/push
      env:
        ACR_NAME: ${{ secrets.ACR_NAME }}
      run: |
        docker build -f gameScoreDocker/Dockerfile . -t $ACR_NAME/gameapi:${{ github.sha }}
        docker push $ACR_NAME/gameapi:${{ github.sha }} 

        docker tag $ACR_NAME/gameapi:${{ github.sha }} $ACR_NAME/gameapi:latest
        docker push $ACR_NAME/gameapi:latest
        
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Get AKS credentials
      env:
        CLUSTER_RESOURCE_GROUP_NAME: ${{ secrets.CLUSTER_RESOURCE_GROUP_NAME }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      run: |
        az aks get-credentials \
          --resource-group $CLUSTER_RESOURCE_GROUP_NAME \
          --name $CLUSTER_NAME \
          --overwrite-existing --admin
    
    - name: Create DB secret in k8s
      run: |
        kubectl create secret generic oladbconnkey --from-literal=cosmos_key=${{ env.cosmos_secret }} --dry-run -o yaml  \
        | kubectl apply -f -

    - name: Create app Insight connection string in k8s
      run: |
        kubectl create secret generic insightsconnectionstring --from-literal=connection_string=${{ env.insight_secret }} --dry-run=client -o yaml \
        | kubectl apply -f -
    
    - name: Deploy application
      uses: Azure/k8s-deploy@v4.6
      with:
          action: deploy
          strategy: basic
          manifests: |
             KubDeployment/deployment.yaml
             KubDeployment/service.yaml
          images: |
             ${{ secrets.ACR_NAME }}/gameapi:${{ github.sha }}


    
      
