name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: gameapicontainer.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -f gameScoreDocker/Dockerfile . -t gameapicontainer.azurecr.io/gameapi:${{ github.sha }}
        docker push gameapicontainer.azurecr.io/gameapi:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'pythongamewebapp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'gameapicontainer.azurecr.io/gameapi:${{ github.sha }}'
